{{- if eq "false" (include "kiali-server.isSkippedResource" (dict "ctx" . "name" "clusterrole")) -}}
{{- if not (or (.Values.deployment.view_only_mode) (ne .Values.auth.strategy "anonymous")) -}}
{{- $namespaces := list "" -}}
{{- if not .Values.deployment.cluster_wide_access -}}
{{- $accessibleNamespacesStr := include "kiali-server.accessible-namespaces" . -}}
{{- $namespaces = splitList "," $accessibleNamespacesStr -}}
{{- end -}}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $.Values.deployment.cluster_wide_access }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ include "kiali-server.fullname" $ }}
{{- if not $.Values.deployment.cluster_wide_access }}
  namespace: {{ $namespace | quote }}
{{- end }}
  labels:
    {{- include "kiali-server.labels" $ | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
{{- if not (has "logs-tab" $.Values.kiali_feature_flags.disabled_features) }}
  - pods/log
{{- end }}
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create
  - post
- apiGroups: ["extensions", "apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - gateway.networking.k8s.io
  - inference.networking.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups: ["apps.openshift.io"]
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs:
  - get
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups: ["oauth.openshift.io"]
  resources:
  - oauthclients
  resourceNames:
  - {{ include "kiali-server.fullname" $ }}-{{ $.Release.Namespace }}
  verbs:
  - get
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
...
{{- end -}} {{/* range $namespace */}}
{{- end -}} {{/* if not view_only_mode and auth.strategy is anonymous */}}
{{- end -}} {{/* if not isSkippedResource */}}
