{{- if eq "false" (include "kiali-server.isSkippedResource" (dict "ctx" . "name" "sa")) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kiali-server.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
...
{{- end -}}
