{{- if eq "false" (include "kiali-operator.isSkippedResource" (dict "ctx" . "name" "clusterrole")) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
  {{- include "kiali-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - list
  - watch
- apiGroups: [""]
  resourceNames:
  - kiali-signing-key
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: [""]
  resourceNames:
  - kiali-multi-cluster-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["kiali.io"]
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["authorization.k8s.io"]
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  {{- if or (and (.Values.cr.create) (.Values.cr.spec.deployment.cluster_wide_access)) (.Values.clusterRoleCreator) }}
  - clusterrolebindings
  - clusterroles
  {{- end }}
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["oauth.openshift.io"]
  resources:
  - oauthclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["config.openshift.io"]
  resources:
  - clusteroperators
  verbs:
  - list
  - watch
- apiGroups: ["config.openshift.io"]
  resourceNames:
  - kube-apiserver
  resources:
  - clusteroperators
  verbs:
  - get
- apiGroups: ["console.openshift.io"]
  resources:
  - consolelinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# The permissions below are for OSSMC operator capabilities
- apiGroups: ["console.openshift.io"]
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["operator.openshift.io"]
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
# The permissions below are for Kiali itself; operator needs these so it can escalate when creating Kiali's roles
- apiGroups: [""]
  resources:
  - configmaps
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - patch
  {{- end }}
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - patch
  {{- end }}
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - patch
  {{- end }}
- apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - inference.networking.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - create
  - delete
  - patch
  {{- end }}
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gateways
  - grpcroutes
  - httproutes
  - referencegrants
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - create
  - delete
  - patch
  {{- end }}
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - delete
  - patch
  {{- end }}
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gatewayclasses
  verbs:
  - get
  - list
  - watch
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - list
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
- apiGroups: ["apps.openshift.io"]
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  {{- if eq .Values.onlyViewOnlyMode false }}
  - patch
  {{- end }}
- apiGroups: ["config.openshift.io"]
  resources:
  - apiservers
  verbs:
  - get
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs:
  - get
{{- end }}
...
{{- end -}}
