---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- include "kiali-operator.annotations" | nindent 4 }}
  labels:
  {{- include "kiali-operator.labels" . | nindent 4 }}
{{- if .Values.image.pullSecrets }}
imagePullSecrets:
{{- range .Values.image.pullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}
...
