name: Helm charts

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Verify Kiali Server permissions
      env:
        YQ_VERSION: v4.40.5
      run: |
        sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
        wget -qO /tmp/yq_checksums "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/checksums"
        echo "$(grep '^yq_linux_amd64 ' /tmp/yq_checksums | awk '{print $19}')  /usr/local/bin/yq" | sha256sum --check
        sudo chmod +x /usr/local/bin/yq
        make verify-kiali-server-permissions

    - name: Build
      run: make build-helm-charts

